spring:
  datasource:
    driver-class-name:
    username:
    password:
    url:
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null
  redis:
    host:
    port:
    password:
wechat:
  mpAppId:
  mpAppSecret:
  mchId:
  mchKey:
  openAppId:
  openAppSecret:
  corpId:
  agentId:
  corpSecret:
  redirectUri:
  keyPath:
  notifyUrl:

project:
  wechatMpAuthorize:
  wechatOpenAuthorize:
  wechatCpAuthorize:
  sell:
server:
  servlet:
    context-path: /sell
